// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOoQnrCCWdwVIPNbzNPIZbL28FcTMsT7U',
    appId: '1:558248438020:web:c1bc74fe129db4013a4851',
    messagingSenderId: '558248438020',
    projectId: 'snipe-vibecheck',
    authDomain: 'snipe-vibecheck.firebaseapp.com',
    storageBucket: 'snipe-vibecheck.appspot.com',
    measurementId: 'G-L0QG3RVJNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnDOHgkdn1moejaIdwZHnBvcrKQxxjr0Y',
    appId: '1:558248438020:android:94b71fbe299d42243a4851',
    messagingSenderId: '558248438020',
    projectId: 'snipe-vibecheck',
    storageBucket: 'snipe-vibecheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSD6VhoJbESrJgVEWUrumyzYVo512BgpQ',
    appId: '1:558248438020:ios:6f6c1f7b129889e73a4851',
    messagingSenderId: '558248438020',
    projectId: 'snipe-vibecheck',
    storageBucket: 'snipe-vibecheck.appspot.com',
    iosClientId: '558248438020-0f8458ilifc1borkdlmggmjhoul502ip.apps.googleusercontent.com',
    iosBundleId: 'com.snipe.app',
  );
}
